name: Validate

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake clang-tidy clang-format libboost-program-options1.83-dev libeigen3-dev libtinyobjloader-dev libstb-dev

      - name: Prepare build commands
        run: cmake . -DPATCH_VERSION=1 -DWITH_TEST=ON

      - name: Check formatting
        run: |
          if ! clang-format --dry-run --Werror -i src/**/*.cpp src/**/*.h; then
            echo "Code formatting issues found. Run 'clang-format -i src/**/*.cpp src/**/*.h' to fix."
            exit 1
          fi

      - name: Static analysis
        run: |
          if ! clang-tidy src/**/*.cpp; then
            echo "Static analysis issues found."
            exit 1
          fi